name: Issue Build Trigger

on:
  issues:
    types: [opened, edited]

jobs:
  trigger-build:
    if: contains(github.event.issue.title, '[BUILD]')
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Body
        id: parse
        uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.issue.body;
            const lines = body.split('\n');
            const config = {};
            lines.forEach(line => {
              const colonIndex = line.indexOf(':');
              if (colonIndex > -1) {
                const key = line.substring(0, colonIndex).trim();
                const value = line.substring(colonIndex + 1).trim();
                if (key && value) {
                  config[key] = value;
                }
              }
            });
            core.setOutput('config', JSON.stringify(config));
            
      - name: Trigger Private Repo Build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          repository: Xwudao/ReMan
          event-type: build-app
          client-payload: |
            {
              "issue_number": "${{ github.event.issue.number }}",
              "issue_url": "${{ github.event.issue.html_url }}",
              "config": ${{ steps.parse.outputs.config }}
            }